# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: token_block_message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import block_message_pb2 as block__message__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19token_block_message.proto\x12\x0c\x65vm_messages\x1a\x13\x62lock_message.proto\"\xb2\x01\n\tTokenInfo\x12\x15\n\rSmartContract\x18\x01 \x01(\x0c\x12\x11\n\tDelegated\x18\x02 \x01(\x08\x12\x13\n\x0b\x44\x65legatedTo\x18\x03 \x01(\x0c\x12\x14\n\x0cProtocolName\x18\x04 \x01(\t\x12\x0c\n\x04Name\x18\x05 \x01(\t\x12\x0e\n\x06Symbol\x18\x06 \x01(\t\x12\x10\n\x08\x44\x65\x63imals\x18\x07 \x01(\x05\x12\x0e\n\x06HasURI\x18\x08 \x01(\x08\x12\x10\n\x08\x46ungible\x18\t \x01(\x08\"\xe3\x01\n\rTokenTransfer\x12\x18\n\x10TransactionIndex\x18\x01 \x01(\x04\x12\x11\n\tCallIndex\x18\x02 \x01(\x04\x12\x10\n\x08LogIndex\x18\x03 \x01(\x04\x12\x0e\n\x06Sender\x18\x04 \x01(\x0c\x12\x10\n\x08Receiver\x18\x05 \x01(\x0c\x12\x0e\n\x06\x41mount\x18\x06 \x01(\x0c\x12\n\n\x02Id\x18\x07 \x01(\x0c\x12\x0b\n\x03URI\x18\x08 \x01(\t\x12)\n\x08\x43urrency\x18\t \x01(\x0b\x32\x17.evm_messages.TokenInfo\x12\x0f\n\x07Success\x18\n \x01(\x08\x12\x0c\n\x04\x44\x61ta\x18\x0c \x01(\x0c\"\x92\x01\n\x11TokenBlockMessage\x12\"\n\x05\x43hain\x18\x01 \x01(\x0b\x32\x13.evm_messages.Chain\x12)\n\x06Header\x18\x02 \x01(\x0b\x32\x19.evm_messages.BlockHeader\x12.\n\tTransfers\x18\x05 \x03(\x0b\x32\x1b.evm_messages.TokenTransferBCZAgithub.com/bitquery/streaming_processor/evm/messages;evm_messagesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'token_block_message_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZAgithub.com/bitquery/streaming_processor/evm/messages;evm_messages'
  _TOKENINFO._serialized_start=65
  _TOKENINFO._serialized_end=243
  _TOKENTRANSFER._serialized_start=246
  _TOKENTRANSFER._serialized_end=473
  _TOKENBLOCKMESSAGE._serialized_start=476
  _TOKENBLOCKMESSAGE._serialized_end=622
# @@protoc_insertion_point(module_scope)
